### ISSUE TITLE
There seems to be a problem with horizontal and vertical

### ISSUE THREAD

**Issue by QSPPPPW** [WolfyScript/CustomCrafting#141] opened 2022-06-20 01:59 UTC
### What happened?

When I change the symmetry, horizontal, vertical, and rotate to true, things like axe and hoe are still invalid and cannot be synthesized symmetrically

### How can the bug be reproduced?

This problem occurs on Minecraft version 1.18.2

### Expected Behaviour?

Can be freely symmetrically synthesized like the original

### Plugin version

CustomCrafting version 3.16.5.0

### Server software

paper Minecraft version 1.18.2

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment] 2022-06-22 14:36
In my tests, it works as intended. Could you send the file of an example recipe that doesn't work?

**Comment by QSPPPPW** [comment] 2022-06-22 15:06
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WolfyScript/CustomCrafting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 晚上10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WolfyScript/CustomCrafting] There seems to be a problem with horizontal and vertical (Issue #141)





 
In my tests, it works as intended. Could you send the file of an example recipe that doesn't work?

**Comment by QSPPPPW** [comment] 2022-06-23 02:58
[e.zip](https://github.com/WolfyScript/CustomCrafting/files/8963292/e.zip)

**Comment by WolfyScript** [comment] 2022-06-25 10:57
Thanks, I found the issue.
The symmetry option isn't loaded correctly, causing to disable all the options. 
It'll be fixed in the next update.

**Closed** 2022-06-25 11:14 UTC
Labels: bug
