### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by SignorPollito** [WolfyScript/CustomCrafting#163] opened 2022-09-02 20:28 UTC
### What happened?

https://github.com/WolfyScript/CustomCrafting/issues/115

### How can the bug be reproduced?

https://github.com/WolfyScript/CustomCrafting/issues/115

### Expected Behaviour?

When crafting more items, the materials inside the crafting rid should not be duplicated

### Plugin version

CustomCrafting 3.16.6.2, WolfyUtilities 4.16.4.1

### Server software

Purpur 1.16.5

### Relevant log output

```shell
/
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment] 2022-09-08 21:21
I was pretty sure this was fixed... hmm
There might be a few things I could try, but this system seems to be very sensitive to changes in Spigot.  
So who knows if the fix I do now fixes it across all Minecraft versions.

Is it possible for you to test out the crafting with the most minimal amount of plugins on another server, like a test server?

On a site note: I am working on contributions for Spigot to provide a better crafting system in the future... I just hope the changes are going to be accepted.

**Comment by SignorPollito** [comment] 2022-09-28 13:03
> Is it possible for you to test out the crafting with the most minimal amount of plugins (best would be just CC and WU) on another server, like a test server?

Sorry for the late responce, even if I tried several times, unfortunately I'm not able to replicate the bug myself, only my players.
I don't think there are plugins that are making some kind of conflicts, the only one that I have on the server and adds crafting recipes is ItemsAdder, but I think he uses the Spigot's API, so it should't be a problem.

It seems to happen only when you SHIFT+Click the recipe result of an unstackable item (like pickaxes, books).
Maybe a solution could be to give the player only one item per click.
Also the bug seems to show up when you spam Shift+Click on recipe result.

The bug still persists.

**Comment by WolfyScript** [comment] 2022-09-30 18:58
Did you enable the recipe to be visible in the vanilla recipe book? 
I'll look into and try to reproduce it with the steps you provided. Maybe I can find something in the existing system that causes this.

I do have a major redesign of the system in works, and I am going to roll it out for cooking recipes soon. Crafting Recipes though will still take a while, but should fix this issue at last (since they would no longer use the Bukkit API).

**Comment by WolfyScript** [comment] 2022-11-22 21:56
Update: This issue should be fixed in the latest update of CustomCrafting and WolfyUtililies!
CC: https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-19-free.55883/update?update=479638
WU: https://github.com/WolfyScript/WolfyUtils-Spigot/releases/tag/v4.16.9.1

**Comment by SignorPollito** [comment] 2022-11-22 22:51
> Update: This issue should be fixed in the latest update of CustomCrafting and WolfyUtililies!
> CC: https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-19-free.55883/update?update=479638
> WU: https://github.com/WolfyScript/WolfyUtils-Spigot/releases/tag/v4.16.9.1

Hi, I have the Premium version of CC, but I noticed that the latest versions of the free and the premium seems different.

They have the same number, but different descriptions of the update (the free one is much much longer).

Are they the same? Or you need to update the Premium one with this fix?

**Comment by WolfyScript** [comment] 2022-11-23 18:51
The reason for the huge change is that it summarizes all the features and bug fixes that the premium version got over a longer period in separate updates.
So the update is the same, but the free changelog includes all the changes since the previous free update.

**Comment by WolfyScript** [comment] 2022-11-25 17:01
Going to close this issue now. 
I really hope the issue is fixed for you all.

Steps to try:
1. look for the option in the config and if missing, add it.
```yml
recipes:
  nms_based_crafting: false
```
2. Observe if the issue is fixed.
3. In case the dupe is still happening, enable the NMS Crafting System
```yml
recipes:
  nms_based_crafting: true
```

Then, if you are still encountering the duplication issue, then it is definitely an incompatibility with another plugin, and I would ask you to open a new issue for it.

**Closed by WolfyScript** 2022-11-25 17:01 UTC
Labels: bug, work in progress
