### ISSUE TITLE
Bug with wind charges when are launched to a cauldron. 1.21 minecraft

### ISSUE THREAD

**Issue by OMarcoGPO** [WolfyScript/CustomCrafting#384] opened 2024-08-03 13:59 UTC
### What happened?

When a wind charge is launched to a cauldron that has already clicked (for the customcrafting gui), the cauldron will provocate a explosion (like a creeper explosion).
![image](https://github.com/user-attachments/assets/231f02e7-915f-4b68-9217-e00960c20e8e)
![image](https://github.com/user-attachments/assets/9baad453-edb8-4724-b832-34b9e92394ab)

### How can the bug be reproduced?

1. Place a cauldron
2. Interact with the cauldron (the bug will not work without this step)
3. Launch a wind charge to the cauldron
4. The bug will happen.

### Expected Behaviour?

The wind charge must not make a explosion

### Plugin version

Customcrafting 4.16.9.1,  WolfyUtilities 4.17-beta.6

### Server software

Paper 1.21

### Relevant log output

```shell
No code error output
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment] 2024-08-09 11:44
That is the weirdest issue I got ever xD 
Neither WolfyUtils nor CustomCrafting should cause explosions like ever, but I did reproduce the issue, so there is definitely something going wrong.   
This one will be interesting to debug. I'll keep you updated about further findings.

**Comment by WolfyScript** [comment] 2024-08-09 12:42
Turns out, Wind Charges use the same explosion event in Spigot as TNT and any other explosions.  
The issue is in the underlying explosion behaviour of the custom block storage (used to store persistent data on blocks) in WolfyUtils, which treats each explosion as destructive.   

I need to figure out to detect different types of explosions and when I am at it improve the code from 2 years ago...  
Spigot added API for this: https://hub.spigotmc.org/jira/browse/SPIGOT-7799  
However, I cannot use the API without dropping support for pre-1.21 versions 🤔   

*No need to understand everything. This is also a note, so future me knows what is going on*

**Closed** 2024-08-12 10:47 UTC
Labels: bug
